### PR TITLE
Added new Tyk sponsor, updated current sponsors. Added step to README

### PR DESCRIPTION
**Pull request by benjiblackstone**
**What Changed?**
Added Tyk as a recurring sponsor to the index page of the website. Removed old recurring sponsors.
Added a small step to the README about updating the theme submodule.

**Why?**
As we are shifting to different sponsors, we need to keep the website up to date.
Without initializing and updating the submodule to load in the minimal them the site does not render locally, and it took me a bit of time to figure that out

### CODE REVIEW

**Comment by myitcv** [comment]
Please can you include a screenshot of the resulting page?

**Comment by myitcv** [comment]
Much like https://github.com/LondonGophers/gophers.london/pull/19#issuecomment-530750903

**Review by domgreen — APPROVED** [review]
Change seem good to me just confirm screenshots with @myitcv

**Comment by benjiblackstone** [comment]
Screenshot from 2020-02-16 12-48-16

This is an image of the page

**Review by myitcv — APPROVED** [review]
Lgtm

**Pull request merged**
